# src-tauri/Cargo.toml
[package]
name = "my-music-app"
version = "0.1.0"
description = "A beautiful music player built with Tauri and Vue"
authors = ["Your Name"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
# Tauri core
tauri = { version = "1.6", features = [
    "shell-open",
    "dialog-all",
    "fs-all",
    "path-all",
    "protocol-asset"
] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
rusqlite = { version = "0.31", features = ["bundled"] }

# Audio metadata
id3 = "1.13"
metaflac = "0.2"

# File system
walkdir = "2"

# Date/Time
chrono = "0.4"

# Async runtime (if needed)
tokio = { version = "1", features = ["full"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
log = "0.4"
env_logger = "0.11"

# Image processing (for album art)
image = "0.25"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[[bin]]
name = "my-music-app"
path = "src/main.rs"
